In [25]:
#Exploring CIA Factbook Data

In [42]:
%%capture
%load_ext sql
%sql sqlite:///factbook.db

'Connected: None@factbook.db'

In [2]:
%%sql
SELECT *
  FROM sqlite_master
 WHERE type='table';

Done.

[('table', 'sqlite_sequence', 'sqlite_sequence', 3, 'CREATE TABLE sqlite_sequence(name,seq)'),
 ('table', 'facts', 'facts', 47, 'CREATE TABLE "facts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "area" integer, "a ... (4 characters truncated) ... land" integer, "area_water" integer, "population" integer, "population_growth" float, "birth_rate" float, "death_rate" float, "migration_rate" float)')]

In [5]:
%%sql
SELECT *
    FROM facts
 LIMIT 5;

Done.

[(1, 'af', 'Afghanistan', 652230, 652230, 0, 32564342, 2.32, 38.57, 13.89, 1.51),
 (2, 'al', 'Albania', 28748, 27398, 1350, 3029278, 0.3, 12.92, 6.58, 3.3),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92),
 (4, 'an', 'Andorra', 468, 468, 0, 85580, 0.12, 8.13, 6.96, 0.0),
 (5, 'ao', 'Angola', 1246700, 1246700, 0, 19625353, 2.78, 38.78, 11.49, 0.46)]

In [7]:
%%sql
SELECT MIN(population), MAX(population), MIN(population_growth), MAX(population_growth)
    FROM facts;

Done.

[('South Sudan', 0, 7256490011, 0.0, 4.02)]

In [8]:
%%sql
SELECT name
    FROM facts
 WHERE population == 0;

Done.

[('Antarctica',)]

In [9]:
%%sql
SELECT name
    FROM facts
 WHERE population == (SELECT MAX(population) FROM facts);

Done.

[('World',)]

In [14]:
%%sql
SELECT MIN(population), MAX(population), MIN(population_growth), MAX(population_growth)
    FROM facts
 WHERE name != 'World' AND name != 'Antarctica';

Done.

[(48, 1367485388, 0.0, 4.02)]

In [19]:
%%sql
SELECT AVG(population), AVG(area)
    FROM facts
 WHERE name != 'World' AND name != 'Antarctica';

Done.

[(32377011.0125, 555093.546184739)]

In [40]:
%%sql
SELECT name as 'Densely Populated Countries', population, area, CAST(population AS FLOAT)/CAST(area AS FLOAT) as 'population/area'
    FROM facts
 WHERE population > (SELECT AVG(population) FROM facts WHERE name != 'World' AND name != 'Antarctica')
    AND area < (SELECT AVG(area) FROM facts WHERE name != 'World' AND name != 'Antarctica')
ORDER BY CAST(population AS FLOAT)/CAST(area AS FLOAT) DESC;

Done.

[('Bangladesh', 168957745, 148460, 1138.0691432035565),
 ('Korea, South', 49115196, 99720, 492.53104693140796),
 ('Philippines', 100998376, 300000, 336.6612533333333),
 ('Japan', 126919659, 377915, 335.8418136353413),
 ('Vietnam', 94348835, 331210, 284.8610700160019),
 ('United Kingdom', 64088222, 243610, 263.0771396904889),
 ('Germany', 80854408, 357022, 226.4689795026637),
 ('Italy', 61855120, 301340, 205.26687462666754),
 ('Uganda', 37101745, 241038, 153.92487906471177),
 ('Thailand', 67976405, 513120, 132.47662340193327),
 ('Poland', 38562189, 312685, 123.3259958104802),
 ('Spain', 48146134, 505370, 95.26907810119319),
 ('Iraq', 37056169, 438317, 84.5419388250969),
 ('Morocco', 33322699, 446550, 74.6225484268279)]

In [32]:
%%sql
SELECT name, CAST(area_water AS FLOAT)/CAST(area_land AS FLOAT) AS "Ratio of Water to Land"
    FROM facts
 ORDER BY CAST(area_water AS FLOAT)/CAST(area_land AS FLOAT)

Done.

[('Ethiopia', None),
 ('New Zealand', None),
 ('South Sudan', None),
 ('Sudan', None),
 ('Holy See (Vatican City)', None),
 ('European Union', None),
 ('Greenland', None),
 ('French Southern and Antarctic Lands', None),
 ('Saint Barthelemy', None),
 ('Saint Martin', None),
 ('Akrotiri', None),
 ('Dhekelia', None),
 ('United States Pacific Island Wildlife Refuges', None),
 ('Antarctica', None),
 ('Arctic Ocean', None),
 ('Atlantic Ocean', None),
 ('Indian Ocean', None),
 ('Pacific Ocean', None),
 ('Southern Ocean', None),
 ('World', None),
 ('Afghanistan', 0.0),
 ('Algeria', 0.0),
 ('Andorra', 0.0),
 ('Angola', 0.0),
 ('Antigua and Barbuda', 0.0),
 ('Bahrain', 0.0),
 ('Barbados', 0.0),
 ('Bhutan', 0.0),
 ('Cabo Verde', 0.0),
 ('Central African Republic', 0.0),
 ('Comoros', 0.0),
 ('Dominica', 0.0),
 ('Equatorial Guinea', 0.0),
 ('Fiji', 0.0),
 ('Georgia', 0.0),
 ('Grenada', 0.0),
 ('Kiribati', 0.0),
 ('Kosovo', 0.0),
 ('Kuwait', 0.0),
 ('Lesotho', 0.0),
 ('Libya', 0.0),
 ('Liechtenstein', 0.0),
 ('Luxembourg', 0.0),
 ('Maldives', 0.0),
 ('Malta', 0.0),
 ('Marshall Islands', 0.0),
 ('Mauritania', 0.0),
 ('Micronesia, Federated States of', 0.0),
 ('Monaco', 0.0),
 ('Nauru', 0.0),
 ('Oman', 0.0),
 ('Palau', 0.0),
 ('Qatar', 0.0),
 ('Saint Kitts and Nevis', 0.0),
 ('Saint Vincent and the Grenadines', 0.0),
 ('San Marino', 0.0),
 ('Sao Tome and Principe', 0.0),
 ('Saudi Arabia', 0.0),
 ('Serbia', 0.0),
 ('Seychelles', 0.0),
 ('Timor-Leste', 0.0),
 ('Trinidad and Tobago', 0.0),
 ('Tuvalu', 0.0),
 ('United Arab Emirates', 0.0),
 ('Vanuatu', 0.0),
 ('Yemen', 0.0),
 ('Ashmore and Cartier Islands', 0.0),
 ('Christmas Island', 0.0),
 ('Cocos (Keeling) Islands', 0.0),
 ('Coral Sea Islands', 0.0),
 ('Heard Island and McDonald Islands', 0.0),
 ('Norfolk Island', 0.0),
 ('Macau', 0.0),
 ('Faroe Islands', 0.0),
 ('Clipperton Island', 0.0),
 ('Saint Pierre and Miquelon', 0.0),
 ('Wallis and Futuna', 0.0),
 ('Aruba', 0.0),
 ('Curacao', 0.0),
 ('Sint Maarten', 0.0),
 ('Cook Islands', 0.0),
 ('Niue', 0.0),
 ('Tokelau', 0.0),
 ('Bouvet Island', 0.0),
 ('Jan Mayen', 0.0),
 ('Svalbard', 0.0),
 ('Anguilla', 0.0),
 ('Bermuda', 0.0),
 ('British Virgin Islands', 0.0),
 ('Cayman Islands', 0.0),
 ('Falkland Islands (Islas Malvinas)', 0.0),
 ('Gibraltar', 0.0),
 ('Guernsey', 0.0),
 ('Jersey', 0.0),
 ('Isle of Man', 0.0),
 ('Montserrat', 0.0),
 ('Pitcairn Islands', 0.0),
 ('Saint Helena, Ascension, and Tristan da Cunha', 0.0),
 ('South Georgia and South Sandwich Islands', 0.0),
 ('Turks and Caicos Islands', 0.0),
 ('American Samoa', 0.0),
 ('Guam', 0.0),
 ('Navassa Island', 0.0),
 ('Northern Mariana Islands', 0.0),
 ('Wake Island', 0.0),
 ('Gaza Strip', 0.0),
 ('Paracel Islands', 0.0),
 ('Spratly Islands', 0.0),
 ('Western Sahara', 0.0),
 ('Bosnia and Herzegovina', 0.0001953621036591322),
 ('Niger', 0.00023683587274019106),
 ('Morocco', 0.000560161326462021),
 ('Guinea', 0.0005697611479873187),
 ('Costa Rica', 0.0007833920877399138),
 ('Djibouti', 0.0008628127696289905),
 ('Korea, North', 0.0010796624808982792),
 ('Cyprus', 0.0010821339681852614),
 ('Namibia', 0.001217068104799038),
 ('Burkina Faso', 0.0014609203798392988),
 ('Congo, Republic of the', 0.0014641288433382138),
 ('Sierra Leone', 0.0016755096341803965),
 ('Honduras', 0.00178746983644651),
 ('Iraq', 0.0021720888864500522),
 ('Samoa', 0.003544842254519674),
 ('Malaysia', 0.0036207961491768015),
 ('South Africa', 0.0038041285499024265),
 ('Peru', 0.004078137744180451),
 ('Thailand', 0.004364931785707295),
 ('Mauritius', 0.0049261083743842365),
 ('France', 0.005268360016051791),
 ('Cameroon', 0.005775211017325633),
 ('Egypt', 0.006027424782761565),
 ('Slovenia', 0.006054290109671977),
 ('Jordan', 0.006080944122880115),
 ('Philippines', 0.006137438374081899),
 ('Portugal', 0.006778178637804745),
 ('Mongolia', 0.006797308883619258),
 ('Uruguay', 0.006856555152415508),
 ('Haiti', 0.006894049346879536),
 ('United Kingdom', 0.006944157400901087),
 ('Belize', 0.00701569762343243),
 ('Dominican Republic', 0.007243377483443708),
 ('Australia', 0.007669578121135597),
 ('Belgium', 0.008256820133430213),
 ('Syria', 0.008440886565376027),
 ('Swaziland', 0.009300162752848175),
 ('Kazakhstan', 0.009334370485609512),
 ('Madagascar', 0.009459366509612408),
 ('Cuba', 0.00947004188672373),
 ('Greece', 0.010027019372813766),
 ('Zimbabwe', 0.010107355104214328),
 ('Mexico', 0.010509556597537481),
 ('Macedonia', 0.011009318601816538),
 ('Croatia', 0.011076571265230286),
 ('Zambia', 0.012402508481324943),
 ('Spain', 0.012806124493967693),
 ("Cote d'Ivoire", 0.014025024921148543),
 ('Bolivia', 0.014105036365700761),
 ('Nigeria', 0.014273667937389104),
 ('Panama', 0.014527845036319613),
 ('Singapore', 0.01455604075691412),
 ('Jamaica', 0.01477241251961961),
 ('Sri Lanka', 0.01516323688689463),
 ('El Salvador', 0.015443270112446311),
 ('Denmark', 0.015553565537069332),
 ('Argentina', 0.015971849204696183),
 ('Guatemala', 0.016144234268703515),
 ('Mali', 0.016392529032363812),
 ('New Caledonia', 0.016415868673050615),
 ('Somalia', 0.016450488334021428),
 ('Saint Lucia', 0.0165016501650165),
 ('Chile', 0.01652299236903949),
 ('Mozambique', 0.016531447900506115),
 ('Lebanon', 0.016617790811339198),
 ('Austria', 0.017296379404451452),
 ('Benin', 0.018079586339064563),
 ('Turkey', 0.018099559269884827),
 ('Tajikistan', 0.018302593456292843),
 ('Brazil', 0.018859459161966657),
 ('Slovakia', 0.01933270969753664),
 ('Chad', 0.019695044472681066),
 ('Kenya', 0.019726253645851635),
 ('Ireland', 0.02017914434621024),
 ('Czech Republic', 0.02097168822090178),
 ('Israel', 0.02164289227742253),
 ('Senegal', 0.02177323014595128),
 ('Bulgaria', 0.022029883213966393),
 ('Papua New Guinea', 0.022037715850373184),
 ('Belarus', 0.023164120256283883),
 ('Paraguay', 0.023785432743857318),
 ('Germany', 0.023948008443465493),
 ('Ecuador', 0.02427386116940771),
 ('Italy', 0.024478139661385734),
 ('Cambodia', 0.025606888932951873),
 ('Laos', 0.025996533795493933),
 ('Botswana', 0.026467630088401885),
 ('Nepal', 0.02671763712844696),
 ('Montenegro', 0.026761819803746655),
 ('Iceland', 0.02743142144638404),
 ('Poland', 0.027707022070302872),
 ('Korea, South', 0.028889806025588115),
 ('China', 0.029009018475490568),
 ('Moldova', 0.029187315679061143),
 ('Switzerland', 0.032002400180013504),
 ('Solomon Islands', 0.03251625812906453),
 ('Hong Kong', 0.032618825722273995),
 ('Pakistan', 0.03271606940165397),
 ('Venezuela', 0.034011677342554274),
 ('Congo, Democratic Republic of the', 0.03432216697661452),
 ('Burma', 0.03530178666519767),
 ('Japan', 0.036846509458551106),
 ('Romania', 0.03697404422095689),
 ('Latvia', 0.03759096531671192),
 ('Hungary', 0.038166235157575217),
 ('Turkmenistan', 0.038665333134722195),
 ('Gabon', 0.03880978161735884),
 ('West Bank', 0.03900709219858156),
 ('Lithuania', 0.041799617102744095),
 ('Ukraine', 0.04180691488443547),
 ('Tonga', 0.04184100418410042),
 ('Kyrgyzstan', 0.04249195781043894),
 ('Russia', 0.04399263341674328),
 ('Togo', 0.044129815206398824),
 ('Azerbaijan', 0.048058187803313605),
 ('Ghana', 0.048344635723169826),
 ('Albania', 0.04927366961092051),
 ('Suriname', 0.05012820512820513),
 ('Indonesia', 0.0513367141963679),
 ('Uzbekistan', 0.051716031969910675),
 ('Tunisia', 0.05310247167868177),
 ('Armenia', 0.054604120129064286),
 ('Norway', 0.06415101780585115),
 ('Estonia', 0.06700009436633009),
 ('Rwanda', 0.06769904329495703),
 ('Vietnam', 0.06817815332021801),
 ('Tanzania', 0.06942876495822985),
 ('United States', 0.07255091319919764),
 ('Iran', 0.07612978626856316),
 ('Burundi', 0.0837227414330218),
 ('Nicaragua', 0.08650720893407784),
 ('French Polynesia', 0.08884243532793311),
 ('Guyana', 0.09205025171578214),
 ('Brunei', 0.0949667616334283),
 ('Colombia', 0.09647636468662751),
 ('Sweden', 0.09738384490720996),
 ('Canada', 0.09799992456155804),
 ('India', 0.10563390940312317),
 ('Finland', 0.11299639583299047),
 ('Taiwan', 0.1153130812151271),
 ('Gambia, The', 0.116600790513834),
 ('Bangladesh', 0.1405085657217485),
 ('Liberia', 0.15623961794019933),
 ('Eritrea', 0.16435643564356436),
 ('Uganda', 0.22292237442922375),
 ('Netherlands', 0.22571032366565366),
 ('Malawi', 0.25939625850340137),
 ('Guinea-Bissau', 0.2846728307254623),
 ('Bahamas, The', 0.3866133866133866),
 ('Puerto Rico', 0.5547914317925592),
 ('Virgin Islands', 4.520231213872832),
 ('British Indian Ocean Territory', 905.6666666666666)]